[package]
name = "word_interleave"
version = "0.3.0"
authors = ["Suchir Kavi <suchirkavi@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"

[profile.release]
debug = true